### ISSUE TITLE
When I select web address harpangell.com/dashboard 

### ISSUE THREAD

**Issue by williamharpCOO** [samyagency/samy#18]
* Version: 2.0.0
* Python: 3.5
* Web Browser: Chrome/Safari/IE/Firefox
* DAPP Browser: Metamask/Cipher

### What was wrong?
When I select web address harpangell.com/dashboard and I'm already logged in as well It loads the Facebook log in for samy for some reason. I hit back and it drops the fb log in samy page and still has dashboard open

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?
Doesn't load samys face ok log in page

Fill this section in if you know how this could or should be fixed.

**Comment by dangell7** [comment]
I need you to elaborate on this more. What is the "Facebook Log in for samy"? What does "drops the fb login samy page" mean?

**Comment by dangell7** [comment]
Can you upload a photo of what you mean?

**Comment by dangell7** [comment]
Is this on mobile? Do you get the same result on the desktop? If not, what browser are you using?

**Comment by dangell7** [comment]
Ok, the reason for this is because you are not logged into facebook. Because the SAMY account is logged into facebook, its asking you to log into your facebook account
