### ISSUE TITLE
Submission Submitted notification

### ISSUE THREAD

**Issue by williamharpCOO** [samyagency/samy#19]
* Version: 2.0.0
* Python: 3.5
* Web Browser: Chrome/Safari/IE/Firefox
* DAPP Browser: Metamask/Cipher

### What was wrong?

Of the creation tab for creating the 11th hour.

It shows creation, brand, submission well when I select the picture and submit a quick sentance or submit pic it goes where or doesn't say you have been submitted please check in on or something for approval.

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by dangell7** [comment]
Closed on Commit
