### ISSUE TITLE
Cannot submit to campaign 11th hr to test 

### ISSUE THREAD

**Issue by williamharpCOO** [samyagency/samy#45]
* Version: 2.0.0
* Python: 3.5
* Web Browser: Chrome/Safari/IE/Firefox
* DAPP Browser: Metamask/Cipher

### What was wrong?

I'm not ranked high enough to create a campaign.

Please include any of the following that are applicable:

* The code which produced the error
* The full output of the error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by dangell7** [comment]
You were trying to submit to a campaign, as a ambassador signed into a brand social media account. I'm closing this for now... Open a new issue if you still have trouble
