### ISSUE TITLE
Error Code when going to harpangell.com/dashboard

### ISSUE THREAD

**Issue by williamharpCOO** [samyagency/samy#8]
* Version: 2.0.0
* Python: 3.5
* Web Browser: Chrome/Safari/IE/Firefox
* DAPP Browser: Metamask/Cipher

### What was wrong?
Did not take me to dashboard harpangell.com/dashboard gave me an error code

Please include any of the following that are applicable:

* The code which produced the error 
Error 505 Ray ID: 405eOd3309e378b6 Bad Gateway
* The full output of the error 
Browser working, Cloudflare working, Host harpangell.com error
* What type of node you were connecting to.

### How can it be fixed?

Fill this section in if you know how this could or should be fixed.

**Comment by dangell7** [comment]
I figured you guys were working so I had taken the site down. In the future, know that this is what you will get if the site it totally down
